<?php
session_start();
require 'db.php';

// If already logged in, skip login page
if (isset($_SESSION['admin_logged_in'])) {
    header("Location: index.php");
        exit;
        }

        $error = "";

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $user = $_POST['username'] ?? '';
                $pass = $_POST['password'] ?? '';

                    try {
                            $stmt = $pdo->prepare("SELECT * FROM v_users WHERE username = ?");
                                    $stmt->execute([$user]);
                                            $userData = $stmt->fetch();

                                                    // Verify password against the hashed version in DB
                                                            if ($userData && password_verify($pass, $userData['password'])) {
                                                                        $_SESSION['admin_logged_in'] = true;
                                                                                    $_SESSION['username'] = $userData['username'];
                                                                                                $_SESSION['role'] = $userData['role']; // Store 'admin' or 'staff'
                                                                                                            
                                                                                                                        header("Location: index.php");
                                                                                                                                    exit;
                                                                                                                                            } else {
                                                                                                                                                        $error = "Invalid Username or Password";
                                                                                                                                                                }
                                                                                                                                                                    } catch (PDOException $e) {
                                                                                                                                                                            $error = "Database Error: " . $e->getMessage();
                                                                                                                                                                                }
                                                                                                                                                                                }
                                                                                                                                                                                ?>
                                                                                                                                                                                <!DOCTYPE html>
                                                                                                                                                                                <html lang="en">
                                                                                                                                                                                <head>
                                                                                                                                                                                    <meta charset="UTF-8">
                                                                                                                                                                                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                                                                            <title>Login | V-ELITE</title>
                                                                                                                                                                                                <script src="https://cdn.tailwindcss.com"></script>
                                                                                                                                                                                                    <style>
                                                                                                                                                                                                            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap');
                                                                                                                                                                                                                    body { font-family: 'Inter', sans-serif; background-color: #020617; }
                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                        <body class="flex items-center justify-center min-h-screen p-6">
                                                                                                                                                                                                                            <div class="w-full max-w-sm bg-slate-900 border border-slate-800 p-8 rounded-3xl shadow-2xl">
                                                                                                                                                                                                                                    <div class="text-center mb-8">
                                                                                                                                                                                                                                                <h1 class="text-4xl font-black italic tracking-tighter text-white">V-ELITE</h1>
                                                                                                                                                                                                                                                            <p class="text-[10px] text-blue-500 font-bold uppercase tracking-widest mt-1">Authorized Access Only</p>
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                            <?php if($error): ?>
                                                                                                                                                                                                                                                                                        <div class="bg-red-500/10 border border-red-500/50 text-red-500 text-[10px] p-3 rounded-xl mb-6 text-center font-bold uppercase tracking-tight">
                                                                                                                                                                                                                                                                                                        <?= $error ?>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                            <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                    <form method="POST" class="space-y-4">
                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                <label class="text-[9px] font-black text-slate-500 uppercase ml-1 tracking-widest">Username</label>
                                                                                                                                                                                                                                                                                                                                                                                <input type="text" name="username" required autofocus
                                                                                                                                                                                                                                                                                                                                                                                                    class="w-full bg-slate-800 border border-slate-700 p-4 rounded-xl text-white outline-none focus:border-blue-500 transition-all font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="text-[9px] font-black text-slate-500 uppercase ml-1 tracking-widest">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="password" name="password" required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class="w-full bg-slate-800 border border-slate-700 p-4 rounded-xl text-white outline-none focus:border-blue-500 transition-all font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-black py-4 rounded-xl uppercase tracking-[0.2em] transition-all active:scale-95 shadow-lg shadow-blue-900/20 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Sign In
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mt-8 pt-6 border-t border-slate-800 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="history.php" class="text-[10px] text-slate-500 font-bold uppercase hover:text-white transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Public Match Archive →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
